[package]
name = "linera_token_creation"
version = "0.1.0"
edition = "2021"

[dependencies]
linera-sdk = "0.12.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
actix-web = "4.0"
tokio = { version = "1", features = ["full"] }